access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}
spring:
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb+srv://momoashraf81:1234@cluster0.wfe13bd.mongodb.net/test
      database: userapp
      auto-index-creation: true
      authentication-database: admin


logging:
  level:
    org.springframework.security: DEBUG
